kind: pipeline
name: default

steps:
  - name: publish-latest
    image: plugins/docker:17.12
    settings:
      registry: ghcr.io
      repo: ghcr.io/e314520513/php-info
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username: e314520513
      dockerfile: Dockerfile
      default_suffix: latest
      password:
        from_secret: docker_password
  - name: publish-1.0.0
    image: plugins/docker:17.12
    settings:
      registry: ghcr.io
      repo: ghcr.io/e314520513/php-info
      auto_tag: true
      auto_tag_suffix: elder-version
      username: e314520513
      dockerfile: Dockerfile-1.0.0
      default_suffix: 1.0.0
      password:
        from_secret: docker_password        
