FROM alpine:3.8

LABEL maintainer="Bo-Yi Wu <applyboy.tw@gmail.com>" \
  org.label-schema.name="Drone Workshop"  \
  org.label-schema.vendor="Bo-yi Wu" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

ADD release/linux/amd64/helloworld /bin/

ENTRYPOINT ["/bin/helloworld"]
